#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: cutover do cache de serving das odds em PRD (DE#109, ADR 0006).
#
# Os passos que SÓ UM HUMANO pode dar, em ordem. Este wizard NÃO foi executado pelo agente que o
# escreveu (nem o dry-run do snapshot, nem nada contra a GCP ou o Supabase): ele abre navegador,
# pede reautenticação e muda IAM, deploy e DDL reais. Rode do checkout da MASTER, com a árvore
# limpa, depois de mergear a pilha inteira (#114 -> #115 -> #116 -> #117 -> este PR).
#
# Cada comando que muda algo pede confirmação antes. Comandos só de leitura rodam direto. Quem
# interromper (Ctrl-C) e rodar de novo refaz os passos: todos são idempotentes ou conferem o
# estado antes de agir (a SA, os papéis e o SQL administrativo já aplicados passam sem erro).
#
# Textos em português (a regra do repositório); a biblioteca acima é a do template e fica como está.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=15

P="${GCP_PROJECT_ID:-smartbetting-dados}"
REGIAO="us-east1"
SA_NOME="sync-bq-postgres"
SA="${SA_NOME}@${P}.iam.gserviceaccount.com"
PY=".venv/bin/python3"
WORKFLOW_YAML="workflow_futebol_sync.yml"
# Linha de base da RPC (estágio 12 grava, estágio 14 compara). Fora da árvore: o estágio 13 faz o PR
# de ligar o cache a partir da master limpa. Sobrescreva com RPC_BASELINE=/outro/caminho.json.
RPC_BASELINE="${RPC_BASELINE:-$HOME/rpc_quotes_pre_cache.json}"

# Raiz do repositório (o wizard vive em scripts/): todos os caminhos abaixo são relativos a ela.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# roda "comando..." mostrando-o antes. Falha do comando NÃO derruba o wizard (set -e): devolve o
# código, e o estágio decide o que fazer.
mostra_e_roda() {
  printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"
  local codigo=0
  "$@" || codigo=$?
  return "$codigo"
}

# so_se_confirmar "pergunta" comando...: só roda o comando que MUDA algo depois do y.
so_se_confirmar() {
  local pergunta="$1"; shift
  if confirm "$pergunta"; then
    mostra_e_roda "$@" || { warn "o comando falhou (código $?). Resolva e rode o wizard de novo."; exit 1; }
  else
    warn "pulado por você; o wizard NÃO segue sem este passo."
    SKIPPED+=("passo recusado: $*")
    exit 1
  fi
}

banner "Cutover do cache de serving das odds em PRD (DE#109)"

# ── 1. Pré-condições: a pilha mergeada e o checkout certo ────────────────
stage "Pré-condições: pilha mergeada, master limpa"
say "Nenhum deploy sai de um checkout que não seja a master: o carimbo de procedência compara"
say "produção com a master (ADR 0001). A pilha da spec #112 tem de estar toda mergeada, NESTA ordem:"
step "#114 (fatia 0) -> #115 (#107) -> #116 (#106) -> #117 (#108) -> o PR da DE#109 (este)."
step "Em cada um: conferir que a base já é a master (gh pr view N --json baseRefName) e o CI verde."
say ""
mostra_e_roda git rev-parse --abbrev-ref HEAD || true
mostra_e_roda git status --short || true
say ""
warn "Esperado: branch 'master', 'git status' sem nenhuma linha, e os 5 PRs MERGEADOS."
confirm "Estou na master atualizada (git pull), com a árvore limpa e a pilha toda mergeada?" \
  || { warn "Mergeie a pilha, faça git checkout master && git pull, e rode de novo."; exit 1; }
[[ "$(git rev-parse --abbrev-ref HEAD)" == "master" ]] || { warn "O checkout não é a master."; exit 1; }
[[ -z "$(git status --porcelain)" ]] || { warn "A árvore não está limpa."; exit 1; }
[[ -f "$PY" ]] || { warn "Falta $PY (ln -s do .venv do checkout principal)."; exit 1; }
[[ -f .env ]] || { warn "Falta o .env (cp do checkout principal)."; exit 1; }

# ── 2. Reautenticar o gcloud ─────────────────────────────────────────────
stage "Reautenticar o gcloud (o deploy completo já perdeu 4 de 29 serviços por reauth)"
say "Precisa de DOIS logins: o do gcloud (deploy, IAM) e o ADC (smoke e snapshot usam a lib Python)."
say "Conta esperada: tecnologia@smartbetting.app."
so_se_confirmar "Rodar 'gcloud auth login' agora (abre o navegador)?" gcloud auth login
so_se_confirmar "Rodar 'gcloud auth application-default login' agora (abre o navegador)?" \
  gcloud auth application-default login
mostra_e_roda gcloud config set project "$P" || true
CONTA=$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | head -n1 || true)
say "Conta ativa: ${CONTA:-nenhuma}"
[[ -n "$CONTA" ]] || { warn "Nenhuma conta ativa no gcloud."; exit 1; }
confirm "A conta ativa é a certa para mexer em IAM e deployar em $P?" || exit 1

# ── 3. Snapshot congelado do universo de odds ────────────────────────────
stage "Snapshot congelado do universo de odds (ANTES de qualquer corte)"
say "A janela 'daily' é recapturada e regravada pelo dbt: o universo de hoje só é refazível se for"
say "congelado AGORA, antes de ligar o corte. O Victor aceitou apontar os scripts de análise para ele."
say "Primeiro o DRY-RUN (só lê metadados e mostra o destino datado):"
mostra_e_roda "$PY" scripts/snapshot_odds_pre_corte.py || { warn "dry-run falhou"; exit 1; }
say ""
so_se_confirmar "Criar o snapshot de verdade (--apply)? Copy job, grátis, ~700 MB de armazenamento." \
  "$PY" scripts/snapshot_odds_pre_corte.py --apply
note "Anote o nome impresso em 'CRIADO': é a tabela para onde o Victor aponta os scripts de análise."
pause "Anotou o nome da tabela congelada?"

# ── 4. SQL administrativo: coluna regra_versao ───────────────────────────
stage "SQL administrativo: a coluna regra_versao do estado de sincronização (DEV e PRD)"
say "Sem a coluna, a imagem nova ABORTA o sync antes de qualquer TRUNCATE (fail-closed). É DDL: só por"
say "psycopg com o .env, nunca pela MCP do Supabase (somente leitura). Idempotente."
say "O .env é lido sem imprimir nenhum valor."
aplica_sql_admin() {
  "$PY" - <<'PYEOF'
import psycopg
from dotenv import dotenv_values

env = dotenv_values(".env")
sql = open("scripts/sql/sync_state_regra_versao.sql", encoding="utf-8").read()
for chave in ("SUPABASE_PG_URL_DEV", "SUPABASE_PG_URL_PRD"):
    with psycopg.connect(env[chave], autocommit=True, connect_timeout=15) as c:
        c.execute(sql)
        linha = c.execute(
            "select column_name, data_type from information_schema.columns "
            "where table_schema = 'futebol' and table_name = '_sync_state' "
            "and column_name = 'regra_versao'"
        ).fetchone()
        print(chave, "->", linha)
        assert linha is not None, f"coluna ausente em {chave}"
PYEOF
}
so_se_confirmar "Aplicar o SQL administrativo no DEV e no PRD (ALTER TABLE ... ADD COLUMN IF NOT EXISTS)?" \
  aplica_sql_admin
note "Esperado: duas linhas 'SUPABASE_PG_URL_* -> ('regra_versao', 'text')'."

# ── 5. Conta de runtime dedicada ao sync ─────────────────────────────────
stage "Conta de runtime DEDICADA ao sync, com o papel de criar query jobs"
say "A permissão bigquery.jobs.create entra numa conta SÓ do sync: a conta compartilhada pelos 29"
say "serviços (ExtractScripts@) NÃO ganha privilégio (história 51 da #112). Conta: $SA"
if gcloud iam service-accounts describe "$SA" --project "$P" >/dev/null 2>&1; then
  say "A conta já existe: pulando a criação."
else
  so_se_confirmar "Criar a conta $SA?" \
    gcloud iam service-accounts create "$SA_NOME" --project "$P" \
      --display-name "Sync BigQuery para Postgres (DE#106/#109/#112)"
fi
so_se_confirmar "Conceder roles/bigquery.jobUser no projeto à $SA_NOME?" \
  gcloud projects add-iam-policy-binding "$P" --member "serviceAccount:$SA" \
    --role roles/bigquery.jobUser --condition=None
for s in SUPABASE_PG_URL_PRD SUPABASE_PG_URL_DEV; do
  so_se_confirmar "Conceder secretAccessor no secret $s à $SA_NOME?" \
    gcloud secrets add-iam-policy-binding "$s" --project "$P" \
      --member "serviceAccount:$SA" --role roles/secretmanager.secretAccessor
done
for d in futebol nba; do
  so_se_confirmar "Conceder dataViewer no dataset $d à $SA_NOME?" \
    bq add-iam-policy-binding --member "serviceAccount:$SA" --role roles/bigquery.dataViewer "$P:$d"
done
note "Se o seu 'bq' recusar add-iam-policy-binding em dataset, adicione a conta como READER no"
note "'access' do dataset (igual ao da ExtractScripts@) pelo console: BigQuery > dataset > Compartilhar."
note "O roles/run.invoker do workflowsde@ fica no serviço e NÃO muda com o redeploy."

# ── 6. Poder impersonar a conta, para o smoke ────────────────────────────
stage "Permissão para impersonar a conta (o smoke roda COMO ela)"
say "O smoke prova a conta dedicada, não a sua: precisa de roles/iam.serviceAccountTokenCreator nela."
so_se_confirmar "Conceder tokenCreator sobre $SA a $CONTA?" \
  gcloud iam service-accounts add-iam-policy-binding "$SA" --project "$P" \
    --member "user:$CONTA" --role roles/iam.serviceAccountTokenCreator
note "IAM leva alguns segundos a propagar: se o smoke do próximo estágio der exit 2, espere e repita."

# ── 7. Smoke ─────────────────────────────────────────────────────────────
stage "Smoke de IAM sob a conta dedicada (sem ele VERDE, não siga)"
say "Dry-run (grátis, nenhuma linha lida, nada escrito): o pré-voo do sync, a leitura filtrada de cada"
say "tabela de DEV com regra e os DOIS query jobs do cache de serving de PRD, com os filtros reais."
say "Esperado: 'VERDE: 12 leitura(s) filtrada(s) ... 0 falha(s)' e exit 0."
say "Exit 1 = falta permissão (a linha FALHA diz a tabela); exit 2 = credencial/impersonation."
while true; do
  if SMOKE_SERVICE_ACCOUNT="$SA" mostra_e_roda "$PY" scripts/smoke_iam_sync_dev.py; then
    break
  fi
  warn "Smoke NÃO está verde."
  confirm "Corrigir o IAM e repetir o smoke?" || { warn "Sem smoke verde não há deploy."; exit 1; }
done

# ── 8. Nenhuma execução ACTIVE ───────────────────────────────────────────
stage "Confirmar que NÃO há execução ACTIVE do workflow-futebol-sync"
say "Redeployar o serviço no meio de um sync mataria a execução em curso (ordem de deploy do usuário)."
say "Saída vazia = nenhuma. O sync roda de hora em hora; espere a janela entre execuções."
note "Esta checagem envelhece: o deploy do workflow (estágio 9) vem depois dela e o sync pode começar"
note "no meio. Por isso ela RODA DE NOVO no estágio 10, colada ao redeploy do serviço."
confere_sem_execucao_active() {
  local ativas
  while true; do
    ativas=$(gcloud workflows executions list workflow-futebol-sync --location="$REGIAO" \
      --project="$P" --filter="state=ACTIVE" --format="value(name,startTime)" --limit=5 2>&1 || true)
    if [[ -z "$ativas" ]]; then
      say "Nenhuma execução ACTIVE."
      return 0
    fi
    warn "Há execução ACTIVE:"
    printf '%s\n' "$ativas"
    confirm "Esperar e conferir de novo?" || { warn "Não redeploye com execução ACTIVE."; exit 1; }
  done
}
confere_sem_execucao_active

# ── 9. Deploy do workflow ANTES da imagem ────────────────────────────────
stage "Deploy do workflow (o YAML vai ANTES da imagem)"
say "O YAML novo manda 'cache_serving' (vazio) ao serviço; a imagem velha o ignora. Com a imagem nova"
say "e o YAML velho nada quebraria, mas a ordem fixada pelo dono é workflow antes da imagem."
note "O cache de serving sai DESLIGADO neste YAML (cache_serving_prd: \"\") e a troca também."
so_se_confirmar "Deployar o workflow-futebol-sync (scripts/deploy_workflows.sh)?" \
  scripts/deploy_workflows.sh workflow-futebol-sync

# ── 10. Deploy da imagem com a conta dedicada ────────────────────────────
stage "Deploy do serviço sync-bq-to-postgres COM a conta dedicada"
say "SYNC_SERVICE_ACCOUNT prende SÓ o sync na conta dedicada; as outras 28 ficam como estão."
say "Sem a variável o serviço voltaria à conta compartilhada, sem jobUser, e o sync abortaria no pré-voo."
say "Antes do redeploy, confere DE NOVO que nenhuma execução começou desde o estágio 8 (o deploy do"
say "workflow e a espera por confirmações passaram no meio e o sync roda de hora em hora):"
confere_sem_execucao_active
so_se_confirmar "Deployar o sync-bq-to-postgres com SYNC_SERVICE_ACCOUNT=$SA_NOME?" \
  env SYNC_SERVICE_ACCOUNT="$SA_NOME" scripts/deploy_cloud_run.sh sync-bq-to-postgres
mostra_e_roda scripts/checa_deriva_servicos.sh sync-bq-to-postgres daily-summary || true
say ""
note "Se a deriva apontar o daily-summary (a pilha #106/#108 mexeu em src/reporting), rode também:"
note "  scripts/deploy_cloud_run.sh daily-summary    (esse CONTINUA na ExtractScripts@)"
confirm "O sync-bq-to-postgres está 'em dia' no detector de deriva?" || exit 1

# ── 11. Primeira execução com o cache DESLIGADO ──────────────────────────
stage "Conferir a primeira execução pós-deploy, com o cache ainda DESLIGADO"
say "Esperado: o DEV (que já filtra mercados servidos + 7 dias) sincroniza as odds sem erro, e o PRD"
say "segue recebendo a tabela completa. Falha aqui = pré-voo de IAM, coluna regra_versao ou smoke mentiu."
step "Abra as execuções do workflow e confira a mais recente (SUCCESS, sem PARTIAL_FAILURE):"
open_url "https://console.cloud.google.com/workflows/workflow/${REGIAO}/workflow-futebol-sync/executions?project=${P}"
step "Aguarde (ou dispare) uma execução depois do deploy e confira a linha 'sync_dev' do log_completion."
confirm "A execução pós-deploy terminou SUCCESS?" || { warn "Investigue antes de ligar o cache."; exit 1; }

# ── 12. Linha de base da RPC (ANTES de ligar o cache) ────────────────────
stage "Linha de base da RPC get_futebol_fixture_quotes (ANTES de ligar o cache)"
say "O critério 'a RPC devolve o mesmo antes e depois' só é executável se o 'antes' for GRAVADO agora:"
say "depois do cache de serving a saída antiga não existe mais. Só LEITURA no PRD (conexão read_only)."
say "Amostra determinística de fixtures com odds em 3 grupos (15 por grupo): recentes (jogo já disputado,"
say "últimos 25 dias; têm de ficar IDÊNTICAS), futuras (a coleta continua: diferença é aviso) e antigas"
say "(>30 dias: só o T-15m sobra; a abertura da Pinnacle, pin_open, some e é aviso). Os ids vão no arquivo,"
say "e o diff do estágio 14 reconsulta os MESMOS ids."
say "Arquivo: $RPC_BASELINE (nunca sobrescrito; apague-o à mão só se for refazer a linha de base ANTES do cache)."
note "Se uma carga de odds estiver em curso (rodam de hora em hora), a consulta pode esperar o lock e"
note "falhar em 90 s com 'statement timeout': espere o fim da carga e rode de novo."
if [[ -f "$RPC_BASELINE" ]]; then
  say "A linha de base já existe: mantida (rode de novo só depois de apagá-la, se estiver velha)."
else
  while true; do
    if CAPTURA_RPC_MODO=captura CAPTURA_RPC_ARQUIVO="$RPC_BASELINE" mostra_e_roda "$PY" scripts/captura_rpc_quotes.py; then
      break
    fi
    warn "A captura falhou."
    confirm "Tentar de novo?" || { warn "Sem linha de base não há como provar o 'antes e depois'."; exit 1; }
  done
fi
note "Esperado: 'GRAVADO ...: N fixtures, M linhas da RPC'. Guarde o arquivo até o diff do estágio 14."
pause "Linha de base gravada?"

# ── 13. Ligar o cache de serving em PRD ──────────────────────────────────
stage "LIGAR o cache de serving das odds em PRD (edição do workflow)"
say "É o ponto sem volta funcional: a próxima carga de PRD grava só os mercados servidos, as fixtures"
say "dos últimos 30 dias e futuras com todas as janelas, e o resto só com o fechamento (T-15m)."
say "Rollback: voltar a linha para \"\" e redeployar o workflow (a versão da regra recarrega a tabela completa)."
say "Isso vale enquanto as odds não estiverem em troca_prd. Depois de ligar a troca (último estágio) o rollback muda: ver lá."
warn "Precisam existir o snapshot do estágio 3 e a linha de base da RPC do estágio 12, e o smoke do estágio 7 tem de estar verde."
confirm "Snapshot criado, linha de base da RPC gravada e smoke verde: ligar?" || exit 1
[[ -f "$RPC_BASELINE" ]] || { warn "Falta a linha de base da RPC ($RPC_BASELINE): depois de ligar o cache ela não se refaz."; exit 1; }
say "Edição (num branch, via PR, como qualquer mudança no master):"
step "git checkout -b liga-cache-serving-odds"
step "No $WORKFLOW_YAML, troque  cache_serving_prd: \"\"  por  cache_serving_prd: \"fact_odds_snapshot\""
step "tests/test_workflow_futebol_sync.py::test_neste_commit_o_cache_de_serving_esta_desligado muda junto."
step "Abra o PR, mergeie, git checkout master && git pull, e só então siga."
pause "PR mergeado e master atualizada?"
so_se_confirmar "Deployar o workflow-futebol-sync com o cache LIGADO?" \
  scripts/deploy_workflows.sh workflow-futebol-sync

# ── 14. Conferir pelo dado ───────────────────────────────────────────────
stage "Conferir pelo DADO (não pelo exit code) depois da primeira carga de PRD com o cache"
say "Critérios de pronto da #109 (spec #112), medidos depois da primeira carga de PRD:"
step "Contagem de linhas de fact_odds_snapshot em PRD entre 0,6 e 1,0 milhão (medido antes: ~1,007 mi;"
step "  vai ficar na beira de cima por causa do mercado 6 e do crescimento; reporte o número exato)."
step "Duração da carga das odds em PRD <= 150 s (campo duracao_s da resposta/log do sync)."
step "A RPC get_futebol_fixture_quotes devolve o MESMO, antes e depois, para a amostra gravada no estágio 12"
step "  (diff por fixture e linha, abaixo); fixtures antigas mostram o fechamento (T-15m)."
step "Sem 503 no edge_logs nem espera de leitor acima de 2 s durante o sync (critério da #108)."
step "Detector de atraso verde nas janelas das 13h UTC (o rebuild que passava de 900 s)."
say ""
say "Diff da RPC contra a linha de base do estágio 12 (SOMENTE leitura; reconsulta os MESMOS ids):"
say "  VERDE (exit 0): nenhuma linha sumiu e as fixtures recentes estão idênticas; avisos são esperados"
say "  em futuras (coleta nova) e antigas (pin_open). VERMELHO (exit 1): linha sumida ou recente alterada."
if confirm "Rodar o diff da RPC agora (SELECT em PRD)?"; then
  CAPTURA_RPC_MODO=diff CAPTURA_RPC_ARQUIVO="$RPC_BASELINE" mostra_e_roda "$PY" scripts/captura_rpc_quotes.py \
    || warn "o diff está VERMELHO (ou falhou): investigue antes de seguir."
fi
say ""
say "Contagem rápida (SOMENTE leitura, sem imprimir segredo):"
conta_odds_prd() {
  "$PY" - <<'PYEOF'
import psycopg
from dotenv import dotenv_values

url = dotenv_values(".env")["SUPABASE_PG_URL_PRD"]
with psycopg.connect(url, connect_timeout=15) as c:
    c.read_only = True
    n = c.execute("select count(*) from futebol.fact_odds_snapshot").fetchone()[0]
    por = c.execute(
        "select market_id, count(*) from futebol.fact_odds_snapshot group by 1 order by 1"
    ).fetchall()
    v = c.execute(
        "select regra_versao from futebol._sync_state where table_name = 'fact_odds_snapshot'"
    ).fetchone()
print("linhas:", n)
print("por mercado:", por)
print("regra_versao:", v)
PYEOF
}
if confirm "Rodar a contagem agora (SELECT em PRD)?"; then
  mostra_e_roda conta_odds_prd || warn "a contagem falhou"
fi
note "O PR da #109 usa 'Refs', não 'Closes': a issue só fecha à mão, depois destes números colados nela"
note "(contagem exata, duração, saída do diff da RPC) e do smoke do BigQuery real."
confirm "Contagem, duração e diff da RPC conferidos e dentro do esperado?" \
  || { warn "Não ligue a troca. Reverta o workflow (cache_serving_prd: \"\") se precisar."; exit 1; }

# ── 15. Ligar a troca nas odds (depois de dezenas de execuções) ──────────
stage "LIGAR a carga por troca nas odds (só depois de dezenas de execuções com o cache)"
say "A odds só entra na troca DEPOIS do filtro (a sombra completa custaria ~+920 MB; com o filtro ~+180 MB)."
say "Ordem de habilitação da spec: ... demais tabelas, e 'fact_odds_snapshot só depois da #109', com"
say "observação de dezenas de execuções entre etapas. O serviço RECUSA a troca das odds sem o cache ligado."
warn "Só prossiga se já passaram dezenas de execuções com o cache ligado, sem regressão de leitura."
warn "ROLLBACK DEPOIS DESTE ESTÁGIO é outro: com fact_odds_snapshot em troca_prd, zerar só"
warn "cache_serving_prd derruba o sync de PRD INTEIRO (o serviço recusa a combinação antes de conectar)."
say "Ordem inversa do ligar: no $WORKFLOW_YAML, tirar fact_odds_snapshot de troca_prd (e de staged_prd, se"
say "estiver lá) E voltar cache_serving_prd: \"\", no MESMO deploy do workflow (scripts/deploy_workflows.sh)."
say "Só tirar a troca (mantendo o cache) também é válido; só zerar o cache, não."
if confirm "Já observei dezenas de execuções com o cache e quero ligar a troca nas odds agora?"; then
  step "git checkout -b liga-troca-odds"
  step "No $WORKFLOW_YAML, acrescente fact_odds_snapshot ao CSV de  troca_prd  (junto das já ligadas)"
  step "PR, merge, git checkout master && git pull, depois:"
  pause "PR mergeado e master atualizada?"
  so_se_confirmar "Deployar o workflow-futebol-sync com a troca das odds LIGADA?" \
    scripts/deploy_workflows.sh workflow-futebol-sync
  note "Conferir depois: duracao_s/troca_ms das odds no log, zero 503 no edge_logs e a sombra sem sobras."
else
  warn "Troca das odds NÃO ligada. Rode de novo (último estágio) quando a observação estiver feita."
  SKIPPED+=("ligar a troca nas odds (troca_prd) depois da observação do cache")
fi

finish
